# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'explore_networks.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1557, 961)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 30, 561, 25))
        self.comboBox.setObjectName("comboBox")
        self.inputDimEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.inputDimEdit.setGeometry(QtCore.QRect(1000, 30, 351, 31))
        self.inputDimEdit.setObjectName("inputDimEdit")
        self.evalBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.evalBrowser.setGeometry(QtCore.QRect(10, 90, 691, 571))
        self.evalBrowser.setObjectName("evalBrowser")
        self.summaryBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.summaryBrowser.setGeometry(QtCore.QRect(720, 90, 821, 571))
        self.summaryBrowser.setObjectName("summaryBrowser")
        self.paramBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.paramBrowser.setGeometry(QtCore.QRect(20, 680, 681, 192))
        self.paramBrowser.setObjectName("paramBrowser")
        self.searchEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.searchEdit.setGeometry(QtCore.QRect(610, 30, 331, 31))
        self.searchEdit.setObjectName("searchEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1390, 30, 131, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1557, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inputDimEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[1,3,224,224]</p></body></html>"))
        self.searchEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dropout</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Refresh"))
